//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Floral_Web_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bouquet
    {
        public bouquet()
        {
            this.sales = new HashSet<sales>();
        }
    
        public int bouquetid { get; set; }
        public string name { get; set; }
        public Nullable<decimal> price { get; set; }
        public string image { get; set; }
        public Nullable<int> cate_id { get; set; }
        public Nullable<int> occasion_id { get; set; }
    
        public virtual category category { get; set; }
        public virtual Occasion Occasion { get; set; }
        public virtual ICollection<sales> sales { get; set; }
    }
}
