//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Floral_Web_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.person = new HashSet<person>();
            this.sales = new HashSet<sales>();
        }
    
        public int custid { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string gender { get; set; }
        public string phone_no { get; set; }
        public string address { get; set; }
    
        public virtual ICollection<person> person { get; set; }
        public virtual ICollection<sales> sales { get; set; }
    }
}
