//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Floral_Web_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public string username { get; set; }
        public string full_name { get; set; }
        public string email { get; set; }
        public string paswrd { get; set; }
        public string account_type { get; set; }
    }
}
