//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Floral_Web_App.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class online_floralEntities : DbContext
    {
        public online_floralEntities()
            : base("name=online_floralEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bouquet> bouquet { get; set; }
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<login> login { get; set; }
        public virtual DbSet<messages> messages { get; set; }
        public virtual DbSet<Occasion> Occasion { get; set; }
        public virtual DbSet<person> person { get; set; }
        public virtual DbSet<sales> sales { get; set; }
    }
}
