//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Floral_Web_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public int Id { get; set; }
        public string To_Name { get; set; }
        public string To_Address { get; set; }
        public string To_Phone_no { get; set; }
        public Nullable<System.DateTime> Delivery_Date { get; set; }
        public Nullable<int> Cust_Id { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
